#!/usr/bin/env bash

# HERE is this script's directory, normalized for symlinks
HERE=$(cd "$(dirname "$(readlink "$BASH_SOURCE" || echo "$BASH_SOURCE")")" && pwd -P)

LEGIBLE=$HERE/vendor/LEGIBLE
source "$LEGIBLE"/sys.bash

# shell directives
sys.wordSplitOnSpaceAndTab  off
sys.globbing                off
sys.aliases                 on

# framework imports
source $LEGIBLE/hash.bash
source $LEGIBLE/in.bash
source $LEGIBLE/os.bash
source $LEGIBLE/out.bash
source $LEGIBLE/str.bash

# our name
PROG=$(basename $0)

USAGE=$(in.readHeredoc <<END
  Do something cool.

  USAGE: $PROG [OPTIONS] [--] [COMMAND]

  Options:

    --help - this message

    --trace - trace execution for debugging

  Commands:

    docool -  do something cool (default if no command supplied)

  Without a command or with docool, $PROG does something cool.
END
)

main () {
  arg=${1:-}

  case $arg in
    ''|docool ) doCool;;
    * )
      sys.rc 2
      sys.die "Unknown argument '$arg'"
      ;;
  esac
}

# doCool does something cool
doCool () {
  out.println "I just did something cool."
}

# globals
COOLNESS=total

# __name__ != '__main__'
sys.sourced? && return

# halt on error
sys.strict on

# option defaults
VERBOSE=0

# parse options
while [[ ${1:-} == -?* ]]; do
  case $1 in
    --help  ) sys.die "$USAGE"  ;;
    --trace ) sys.trace on      ;;
    -v      ) VERBOSE=1         ;;
    -- )
      shift
      break
      ;;
  esac
  shift
done

main $*
